# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 17:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ideareg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1, null=True, verbose_name=b'What sex are you?')),
                ('phoneNumber', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex=b'^\\+?1?\\d{10}$')])),
                ('mailId', models.EmailField(max_length=254)),
                ('ideaTitle', models.CharField(max_length=20, verbose_name=b'maximum limit 20 characters')),
                ('idea', models.CharField(max_length=200)),
            ],
        ),
    ]
