# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideareg',
            name='ideaTitle',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ideareg',
            name='mailId',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='ideareg',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ideareg',
            name='sex',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1, verbose_name=b'SEX   '),
        ),
    ]
