# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20161202_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideareg',
            name='idea',
            field=models.TextField(max_length=200),
        ),
    ]
