# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20161202_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideareg',
            name='mailId',
            field=models.EmailField(max_length=11),
        ),
        migrations.AlterField(
            model_name='ideareg',
            name='sex',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1, verbose_name=b'Gender      '),
        ),
    ]
