# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161202_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideareg',
            name='idea',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ideareg',
            name='ideaTitle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ideareg',
            name='mailId',
            field=models.EmailField(max_length=50),
        ),
    ]
