# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-20 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20161202_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='addques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('question', models.TextField(max_length=100)),
                ('timetaken', models.IntegerField(default=0)),
                ('idForum', models.IntegerField(default=-999999)),
            ],
        ),
    ]
