# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-26 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20161226_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrated',
            name='sex',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1, verbose_name=b'Gender '),
        ),
    ]
