# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-26 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20161226_2317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registrated',
        ),
        migrations.AddField(
            model_name='ideareg',
            name='accessToIdea',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='ideareg',
            name='headOfIdea',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
