# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20161226_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=100)),
                ('ideaname', models.CharField(max_length=20)),
                ('timetaken', models.IntegerField(default=0)),
            ],
        ),
    ]
