# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_chatted_ideaid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chatted',
        ),
    ]
