# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_chatted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideareg',
            name='ideaFile',
            field=models.FileField(default=None, upload_to=b'uploads/'),
        ),
    ]
