# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_ideareg_ideafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideareg',
            name='idea',
            field=models.TextField(max_length=100, verbose_name=b'Short Description of Idea(in 30-50 words)'),
        ),
    ]
