# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20161228_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ideareg',
            new_name='idearegistration',
        ),
    ]
