# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20161228_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='idearegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1, verbose_name=b'Gender      ')),
                ('phoneNumber', models.CharField(blank=True, max_length=10)),
                ('mailId', models.EmailField(max_length=50)),
                ('ideaTitle', models.CharField(max_length=50)),
                ('idea', models.TextField(max_length=100, verbose_name=b'Short Description of Idea(in 30-50 words)')),
                ('headOfIdea', models.IntegerField(default=0, max_length=1)),
                ('accessToIdea', models.IntegerField(default=0, max_length=1)),
                ('ideaFile', models.FileField(default=None, upload_to=b'uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='idearegistration',
        ),
    ]
