# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20161228_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idearegister',
            name='ideaFile',
            field=models.FileField(upload_to=b'uploads/'),
        ),
    ]
