# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20161228_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idearegister',
            name='accessToIdea',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='idearegister',
            name='headOfIdea',
            field=models.IntegerField(default=0),
        ),
    ]
