# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20161228_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='idearegister',
            name='checked',
            field=models.IntegerField(default=0),
        ),
    ]
